---
abstract: "INGY's Alternate version of Sex"
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alt-Sex-INGY
no_index:
  directory:
    - inc
    - t
    - xt
    - example
  file:
    - lib/Sex.pm
requires:
  perl: v5.8.1
resources:
  bugtracker: https://github.com/ingydotnet/alt-sex-ingy-pm/issues
  homepage: https://github.com/ingydotnet/alt-sex-ingy-pm
  repository: https://github.com/ingydotnet/alt-sex-ingy-pm.git
version: '0.09'
